### ISSUE TITLE
Beacon port not set correctly

### ISSUE THREAD

**Issue by RandomFunctionForUsername** [Didstopia/satisfactory-server#8]
**Describe the bug**

Beacon port not set correctly using docker-compose

**docker-compose file**

```
version: '3'
services:
    satisfactory-server:
        container_name: 'satisfactory-server2'
        hostname: 'satisfactory-server2'
        image: 'didstopia/satisfactory-server:latest'
        ports:
            - '17778:17778/udp'
            - '15001:15001/udp'
            - '15778:15778/udp'
        volumes:
            - '/opt/satisfactory2/gamefiles:/steamcmd/satisfactory'
            - '/opt/satisfactory2/saves:/app/.config'
        environment:
            - TZ="Europe\Amsterdam"
            - PGID=1000
            - PUID=1000
            - SATISFACTORY_LISTEN_PORT="17778"
            - SATISFACTORY_BEACON_PORT="15001"
            - SATISFACTORY_SERVER_QUERY_PORT="15778"
            - SATISFACTORY_BRANCH="public"
        restart: unless-stopped
```

**Expected behavior**
The beacon port set to 15001

**Environment (please complete the following information):**
 - Docker 20.10.14, build a224086
 - using Portainer 2.11.1

**Last 10 Container log lines**
```
[2022.04.24-19.15.10:681][  0]PacketHandlerLog: Loaded PacketHandler component: Engine.EngineHandlerComponentFactory (StatelessConnectHandlerComponent)
[2022.04.24-19.15.10:681][  0]LogNet: GameNetDriver EOSNetDriver_2147482558 IpNetDriver listening on port 17778
[2022.04.24-19.15.10:682][  0]LogWorld: Bringing World /Game/FactoryGame/Map/DedicatedserverEntry.DedicatedserverEntry up for play (max tick rate 30) at 2022.04.24-19.15.10
[2022.04.24-19.15.10:689][  0]LogWorld: Bringing up level for play took: 0.007468
[2022.04.24-19.15.10:690][  0]LogGameMode: Display: Match State Changed from EnteringMap to WaitingToStart
[2022.04.24-19.15.10:690][  0]LogGameState: Match State Changed from EnteringMap to WaitingToStart
[2022.04.24-19.15.10:692][  0]LogReplicationGraph: Display: SetActorDiscoveryBudget set to 20 kBps (5333 bits per network tick).
[2022.04.24-19.15.10:693][  0]LogNetCore: DDoS detection status: detection enabled: 0 analytics enabled: 0
[2022.04.24-19.15.10:693][  0]LogInit: BSD IPv4/6: Socket queue. Rx: 262144 (config 131072) Tx: 262144 (config 131072)
[2022.04.24-19.15.10:693][  0]LogNet: Created socket for bind address: 0.0.0.0 on port 15000
```

As you can see port 17778 is set correctly, 15001 is not.
